# Generated by Django 5.2.16 on 2026-07-20 15:49

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Projects index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(help_text='A short one-line summary. Also used as the fallback meta description.', max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('quote', 8), ('embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('size', 1)]], {}), 3: ('base.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen reader users. Required.', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 0), ('attribution', 6)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('url', 9), ('caption', 6)]], {})})),
                ('repo_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('live_url', models.URLField(blank=True, verbose_name='Live demo URL')),
                ('date', models.DateField(help_text='Used for ordering and display.')),
                ('featured', models.BooleanField(default=False, help_text='Featured projects are highlighted on the home page.')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(help_text='Describe the image for screen reader users.', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.projectpage')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='technologies',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.technology'),
        ),
    ]
