# Generated by Django 5.2.16 on 2026-07-20 17:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('quote', 8), ('embed', 10), ('code', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('size', 1)]], {}), 3: ('base.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen reader users. Required.', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('quote', 0), ('attribution', 6)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('url', 9), ('caption', 6)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional, e.g. 'settings.py'.", 'max_length': 255, 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('php', 'PHP'), ('bash', 'Bash / shell'), ('yaml', 'YAML'), ('json', 'JSON'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('go', 'Go'), ('docker', 'Dockerfile'), ('text', 'Plain text')]}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('filename', 11), ('language', 12), ('code', 13)]], {})}),
        ),
    ]
