# Generated by Django 5.2.16 on 2026-07-20 15:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('hero', 8), ('featured_projects', 11), ('latest_posts', 13), ('call_to_action', 15), ('heading', 17), ('paragraph', 18), ('image', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen reader users. Leave blank only if the image is purely decorative.', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('external_url', 6)]], {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('image', 2), ('image_alt_text', 3), ('button', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Featured projects', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'max_value': 12, 'min_value': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 9), ('count', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Latest posts', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 12), ('count', 10)]], {}), 14: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('external_url', 6)]], {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('button', 14)]], {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('size', 16)]], {}), 18: ('base.blocks.RichTextBlock', (), {}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen reader users. Required.', 'max_length': 255, 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('image', 19), ('alt_text', 20), ('caption', 1)]], {})}),
        ),
    ]
