# Generated by Django 5.2.16 on 2026-07-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_certificate'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='resume_pdf_pt',
            field=models.ForeignKey(blank=True, help_text='Optional. If provided, a second download link is shown alongside the English resume.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Resume (PDF, Português)'),
        ),
    ]
